# Generated by Django 6.0.4 on 2026-04-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beekeeper',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
