# Generated by Django 5.2.14 on 2026-05-06 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
        ("users", "0002_beekeeper_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={
                "ordering": ["-registered_at"],
                "verbose_name": "جهاز",
                "verbose_name_plural": "الأجهزة",
            },
        ),
        migrations.RemoveField(
            model_name="device",
            name="device_id",
        ),
        migrations.AddField(
            model_name="device",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="mac_address",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                unique=True,
                verbose_name="MAC Address",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="ملاحظات"),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.CharField(
                choices=[("MASTER", "ماستر"), ("SLAVE", "تابع")],
                default="MASTER",
                max_length=10,
                verbose_name="نوع الجهاز",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="firmware_version",
            field=models.CharField(
                default="1.0.0", max_length=20, verbose_name="إصدار البرنامج"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="is_online",
            field=models.BooleanField(default=False, verbose_name="متصل الآن"),
        ),
        migrations.AlterField(
            model_name="device",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True, verbose_name="آخر ظهور"),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(max_length=100, verbose_name="اسم الجهاز"),
        ),
        migrations.AlterField(
            model_name="device",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slaves",
                to="devices.device",
                verbose_name="الجهاز الأب",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="registered_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاريخ التسجيل"),
        ),
        migrations.AlterField(
            model_name="device",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="users.beekeeper",
                verbose_name="النحّال",
            ),
        ),
    ]
