# Generated by Django 5.2.14 on 2026-05-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_alter_device_options_remove_device_device_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorizedMAC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        max_length=17, unique=True, verbose_name="MAC Address"
                    ),
                ),
                (
                    "is_registered",
                    models.BooleanField(default=False, verbose_name="مسجل من نحّال"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
            ],
            options={
                "verbose_name": "جهاز مرخص",
                "verbose_name_plural": "الأجهزة المرخصة",
                "db_table": "authorized_macs",
            },
        ),
    ]
