# Generated by Django 6.0.4 on 2026-04-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('firmware_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
                ('device_type', models.CharField(choices=[('MASTER', 'Master'), ('SLAVE', 'Slave')], max_length=10)),
                ('file_path', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('checksum', models.CharField(max_length=64)),
                ('changelog', models.TextField(blank=True)),
                ('is_stable', models.BooleanField(default=True)),
                ('min_version', models.CharField(blank=True, max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Firmware',
                'verbose_name_plural': 'Firmwares',
                'db_table': 'firmware',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
