# Generated by Django 6.0.4 on 2026-04-19 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('firmware', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTASession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DOWNLOADING', 'Downloading'), ('VERIFYING', 'Verifying'), ('APPLYING', 'Applying'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firmware.firmware')),
            ],
            options={
                'verbose_name': 'OTA Session',
                'verbose_name_plural': 'OTA Sessions',
                'db_table': 'ota_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
