# Generated by Django 5.2.13 on 2026-04-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firmware", "0002_otasession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otasession",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
