# Generated by Django 6.0.4 on 2026-04-19 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('temperature_1', models.FloatField(blank=True, null=True)),
                ('temperature_2', models.FloatField(blank=True, null=True)),
                ('temperature_3', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('co2', models.IntegerField(blank=True, null=True)),
                ('sound', models.IntegerField(blank=True, null=True)),
                ('light_level', models.IntegerField(blank=True, null=True)),
                ('uv_index', models.IntegerField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('battery_health', models.IntegerField(blank=True, null=True)),
                ('signal_rssi', models.IntegerField(blank=True, null=True)),
                ('motion_detected', models.BooleanField(default=False)),
                ('vibration_detected', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('NORMAL', 'Normal'), ('SWARMING', 'Swarming'), ('SICK', 'Sick'), ('QUEENLESS', 'Queenless'), ('HONEY_FLOW', 'Honey Flow'), ('WINTERING', 'Wintering'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device')),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'db_table': 'sensor_readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='sensor_read_device__8811cc_idx')],
            },
        ),
    ]
