# Generated by Django 6.0.4 on 2026-04-19 12:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialkey',
            name='key',
            field=models.CharField(default=accounts.models.generate_serial_key, max_length=20, unique=True),
        ),
    ]
