# Generated by Django 6.0.4 on 2026-04-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_serialkey_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serialkey',
            name='device_type',
        ),
    ]
